# Generated by Django 5.1.2 on 2024-10-30 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 29, 6, 667194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='receive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 29, 6, 670194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 29, 6, 670194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfersale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 29, 6, 671195, tzinfo=datetime.timezone.utc)),
        ),
    ]
