# Generated by Django 5.1.2 on 2024-11-04 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_billpayment_date_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 3, 56, 15, 544441, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sold_out',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_in',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 3, 56, 15, 555178, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 3, 56, 15, 557225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfersale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 3, 56, 15, 560507, tzinfo=datetime.timezone.utc)),
        ),
    ]
