# Generated by Django 5.1.2 on 2024-11-08 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_billpayment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 3, 43, 55, 265471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 3, 43, 55, 269631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 3, 43, 55, 269631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfersale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 3, 43, 55, 270650, tzinfo=datetime.timezone.utc)),
        ),
    ]
